# Generated by Django 4.2.4 on 2023-10-04 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name[ja]')),
                ('name_tr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name[tr]')),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name[en]')),
                ('name_ky', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name[ky]')),
                ('name_kz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name[kz]')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description[ja]')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Description[tr]')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description[ru]')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description[en]')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Description[ky]')),
                ('description_kz', models.TextField(blank=True, null=True, verbose_name='Description[kz]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deactivated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='promotions.banner')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', related_query_name='promotion', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='promotions.promotion')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
