# Generated by Django 4.2.4 on 2023-11-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_kz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name_kz',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name_tr',
        ),
    ]
