# Generated by Django 4.2.4 on 2024-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('link', 'Link'), ('promotion', 'Promotion')], default='promotion', max_length=20),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name[ja]'),
        ),
    ]
