# Generated by Django 4.2.4 on 2023-10-04 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import product.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[ja]')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[en]')),
                ('name_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[tr]')),
                ('name_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[ky]')),
                ('name_kz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[kz]')),
                ('deactivated', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=product.utils.internal_product_id_generation, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name[ja]')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description[ja]')),
                ('rakuten_price', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('product_url', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reference_rank', models.IntegerField(blank=True, null=True)),
                ('name_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name[tr]')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name[en]')),
                ('name_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name[ky]')),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name[kz]')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Description[tr]')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description[ru]')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description[en]')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Description[ky]')),
                ('description_kz', models.TextField(blank=True, null=True, verbose_name='Description[kz]')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[tr]')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[en]')),
                ('name_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[ky]')),
                ('name_kz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[kz]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[tr]')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[en]')),
                ('name_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[ky]')),
                ('name_kz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name[kz]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.taggroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
            ],
            managers=[
                ('analytics', django.db.models.manager.Manager()),
            ],
        ),
    ]
