# Generated by Django 4.2.4 on 2023-08-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name[ja]')),
                ('name_tr', models.CharField(blank=True, max_length=255, verbose_name='Name[tr]')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name[en]')),
                ('name_ky', models.CharField(blank=True, max_length=255, verbose_name='Name[ky]')),
                ('name_de', models.CharField(blank=True, max_length=255, verbose_name='Name[de]')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Name[ja]')),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('name_tr', models.CharField(blank=True, max_length=255, verbose_name='Name[tr]')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name[en]')),
                ('name_ky', models.CharField(blank=True, max_length=255, verbose_name='Name[ky]')),
                ('name_de', models.CharField(blank=True, max_length=255, verbose_name='Name[de]')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rakuten_id', models.CharField(max_length=32, unique=True)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('marker_code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=500, verbose_name='Name[ja]')),
                ('name_tr', models.CharField(blank=True, max_length=500, verbose_name='Name[tr]')),
                ('name_ru', models.CharField(blank=True, max_length=500, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=500, verbose_name='Name[en]')),
                ('name_ky', models.CharField(blank=True, max_length=500, verbose_name='Name[ky]')),
                ('name_de', models.CharField(blank=True, max_length=500, verbose_name='Name[de]')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description[ja]')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Description[tr]')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description[ru]')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description[en]')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Description[ky]')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Description[de]')),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('product_url', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='products', related_query_name='product', to='product.genre')),
                ('marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.marker')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name[ja]')),
                ('name_tr', models.CharField(blank=True, max_length=500, verbose_name='Name[tr]')),
                ('name_ru', models.CharField(blank=True, max_length=500, verbose_name='Name[ru]')),
                ('name_en', models.CharField(blank=True, max_length=500, verbose_name='Name[en]')),
                ('name_ky', models.CharField(blank=True, max_length=500, verbose_name='Name[ky]')),
                ('name_de', models.CharField(blank=True, max_length=500, verbose_name='Name[de]')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Value[ja]')),
                ('value_tr', models.TextField(blank=True, null=True, verbose_name='Value[tr]')),
                ('value_ru', models.TextField(blank=True, null=True, verbose_name='Value[ru]')),
                ('value_en', models.TextField(blank=True, null=True, verbose_name='Value[en]')),
                ('value_ky', models.TextField(blank=True, null=True, verbose_name='Value[ky]')),
                ('value_de', models.TextField(blank=True, null=True, verbose_name='Value[de]')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='GenreChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='product.genre')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.genre')),
            ],
        ),
    ]
