# Generated by Django 4.2.4 on 2023-10-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.RenameField(
            model_name='producttranslation',
            old_name='caption',
            new_name='catch_copy',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
