version: "3.9"

services:
  celery-beat-dev:
    container_name: celery-beat-dev
    restart: always
    build:
      context: ../../
    command: celery --app kaimon beat --loglevel=info
    env_file:
      - ../../.env

  celery-mailing-dev:
    container_name: celery-mailing-dev
    hostname: celery-mailing-dev
    restart: always
    build:
      context: ../../
    command: celery --app kaimon worker -Q mailing -c 1 --loglevel=info
    env_file:
      - ../../.env

  celery-rakuten-requests-dev:
      container_name: celery-rakuten-requests-dev
      hostname: celery-genre-requests-dev
      restart: always
      build:
        context: ../../
      command: celery --app kaimon worker -Q genre_requests -c 2 --loglevel=info
      env_file:
        - ../../.env

  celery-item-saving-dev:
    container_name: celery-genre-requests-dev
    hostname: celery-genre-requests-dev
    restart: always
    build:
      context: ../../
    command: celery --app kaimon worker -Q item_saving -c 25 --loglevel=info
    env_file:
      - ../../.env

  web-kaimon-dev:
    container_name: web-kaimon-dev
    restart: always
    build:
      context: ../../
    entrypoint: ["bash", "./deploy/entrypoint.sh"]
    env_file:
      - ../../.env
    expose:
      - "8334"
    volumes:
      - static:/app/static
      - media:/app/media

  nginx-kaimon-dev:
    container_name: nginx_kaimon_dev
    restart: always
    build:
      context: ../../
      dockerfile: deploy/dev/nginx.Dockerfile
    ports:
      - "9010:80"
    depends_on:
      - web-kaimon-dev
    volumes:
      - static:/app/static
      - media:/app/media


volumes:
  static:
  media:
