version: "3.9"

services:
  postgres:
    image: postgres
    shm_size: 512m
    restart: always
    networks:
      - database
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: kaimono
      POSTGRES_PASSWORD: lksdflkma12ke0291
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass akmsdokm124j90
    networks:
      - redis_cache
    ports:
      - "6355:6379"
    volumes:
      - redis_data:/usr/local/etc/redis

  web:
    restart: always
    build:
      context: ../../
    networks:
      - backend
      - database
      - redis_cache
    entrypoint: [ "bash", "./deploy/sh/entrypoint.sh" ]
    env_file:
      - ../../.env
    expose:
      - "8334"
    volumes:
      - static:/app/static
      - media:/app/media

  nginx-dev:
    container_name: nginx-dev
    restart: always
    networks:
      - backend
    build:
      context: ../../
      dockerfile: deploy/dev/nginx.Dockerfile
    ports:
      - "9010:80"
    depends_on:
      - web
    volumes:
      - static:/app/static
      - media:/app/media

  celery-default:
    restart: always
    build:
      context: ../../
    networks:
      - database
      - redis_cache
    command: celery --app kaimon worker -Q default -c 4 --loglevel=info
    env_file:
      - ../../.env
    depends_on:
      - web

  celery-beat:
    restart: always
    build:
      context: ../../
    networks:
      - database
      - redis_cache
    command: celery --app kaimon beat --loglevel=info
    env_file:
      - ../../.env
    depends_on:
      - web

  celery-mailing:
    restart: always
    build:
      context: ../../
    networks:
      - database
      - redis_cache
    command: celery --app kaimon worker -Q mailing -c 1 --loglevel=info
    env_file:
      - ../../.env
    depends_on:
      - web

  celery-rakuten-requests:
    restart: always
    build:
      context: ../../
    networks:
      - database
      - redis_cache
    command: celery --app kaimon worker -Q rakuten_requests -c 3 --loglevel=info
    env_file:
      - ../../.env
    depends_on:
      - web

  celery-item-saving:
    restart: always
    build:
      context: ../../
    networks:
      - database
      - redis_cache
    command: celery --app kaimon worker -Q item_saving -c 4 --loglevel=info
    env_file:
      - ../../.env
    depends_on:
      - web

networks:
  backend:
    driver: bridge

  database:
    driver: bridge

  redis_cache:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  static:
  media:
