# Generated by Django 4.2.4 on 2023-11-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(choices=[('usd', 'Dollar'), ('som', 'Som'), ('yen', 'Yen')], default='yen', max_length=10)),
                ('currency_to', models.CharField(choices=[('usd', 'Dollar'), ('som', 'Som'), ('yen', 'Yen')], max_length=10)),
                ('price_per', models.DecimalField(decimal_places=10, help_text='unit price currency_from', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
