# Generated by Django 4.2.4 on 2024-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='currency_from',
            field=models.CharField(choices=[('usd', 'Dollar'), ('som', 'Som'), ('yen', 'Yen'), ('moneta', 'Moneta')], default='yen', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='currency_to',
            field=models.CharField(choices=[('usd', 'Dollar'), ('som', 'Som'), ('yen', 'Yen'), ('moneta', 'Moneta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='price_per',
            field=models.DecimalField(decimal_places=2, help_text='unit price currency_from', max_digits=20),
        ),
    ]
