# Generated by Django 4.2.4 on 2023-10-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth2Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.BigIntegerField(unique=True)),
                ('secret', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=35, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('to_validation', models.BooleanField(default=False)),
            ],
        ),
    ]
