# Generated by Django 4.2.4 on 2023-11-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_receipt_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='site_currency',
            field=models.CharField(choices=[('usd', 'Dollar'), ('som', 'Som'), ('yen', 'Yen')], default='yen', max_length=5),
            preserve_default=False,
        ),
    ]
