# Generated by Django 4.2.4 on 2023-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_receipt_site_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bayer_code',
            field=models.CharField(default='t1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
