# Generated by Django 4.2.4 on 2024-02-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_monetainvoice_deliveryaddress_as_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment', serialize=False, to='orders.order')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('paybox', 'Paybox'), ('moneta', 'Moneta')], default='paybox', max_length=10)),
                ('payment_link', models.URLField(max_length=700)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('payment_meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymenttransactionreceipt',
            name='order',
        ),
        migrations.DeleteModel(
            name='MonetaInvoice',
        ),
        migrations.DeleteModel(
            name='PaymentTransactionReceipt',
        ),
    ]
