# Generated by Django 4.2.4 on 2023-11-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_customer_bayer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipping',
            name='shipping_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
