# Generated by Django 4.2.4 on 2023-10-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.tag'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='order.order'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipts', to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='order.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='order.deliveryaddress'),
        ),
    ]
