"""
Django settings for kaimon project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # JS for testing
    "http://176.126.166.140:9010",
    "http://176.126.166.140",
    "http://localhost:9010",

]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'django_celery_beat',
    'drf_spectacular',

    'users',
    'product',
    'rakuten_scraping',
    'order',
    'promotions',
    'currencies',
    'external_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kaimon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kaimon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT', cast=int, default=5432)
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'kaimono-static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = 'kaimono-media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = ['users.backends.EmailOrUsernameAuthBackend']
LOGIN_URL = '/admin/login/'

CORS_ALLOW_ALL_ORIGINS = True  # for testing

REDIS_CONNECTION_URL = config("REDIS_URL")
CELERY_BROKER_URL = REDIS_CONNECTION_URL + '/0'
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = REDIS_CONNECTION_URL + '/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CONNECTION_URL + '/0'
    },
    "users": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CONNECTION_URL + '/1'
    },
    "scraping": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CONNECTION_URL + '/2'
    },

}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=31),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": config('VERIFYING_KEY', default=""),
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Kaimono Project API',
    'DESCRIPTION': '',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True
}

RESTORE_SETTINGS = {
    "CACHE_NAME": "users",
    "CODE_PREFIX": "restore_code:",
    "CODE_ALLOWED_CHARS": "0123456789",
    "CODE_LIVE_SECONDS": 600,
    "TOKEN_PREFIX": "restore_token:",
    "TOKEN_LEN": 6,
    "TOKEN_LIVE_SECONDS": 1200,
    "TOKEN_ALGORITHM": "HS256",
    "MAIL_SUBJECT": ""
}

RAKUTEN_PARSING_SETTINGS = {
    'CACHE_NAME': "scraping"
}

SENDGRID_API_KEY = config('SENDGRID_API_KEY')
MAILING_FROM_EMAIL = config('MAILING_FROM_EMAIL')
RESTORE_VERIFY_CODE_TEMPLATE_ID = config("RESTORE_CODE_TEMPLATE_ID")
RESTORE_VERIFY_TEMPLATE = {
    "subject": "Verification code",
    "code": "",
    "warning_text": "if it wasn't you. Please ignore this message and do not share the code with anyone."
}

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'  # this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
EMAIL_PORT = 587  # 587 for TLS 465 for ssl
EMAIL_USE_TLS = True

SUPPORTED_LANG = ('ru', 'en', 'ja', 'tr', 'ky', 'kz')
VERBOSE_LANGUAGES = {'ja': '日本語', 'ru': 'Русский', 'en': 'English', 'tr': 'Türkçe', 'ky': 'Кыргызча', 'kz': 'Қазақ'}
TRANSLATE_LANGUAGES = {
    'ru': 'ru',
    'en': 'en',
    'tr': 'tr',
    # 'ky': 'ky',
    # 'kz': 'kk'
}
TRANSLATE_DELAY = 0.25
LANGUAGE_QUERY_PARAM = 'lang'
CURRENCY_QUERY_PARAM = 'currency'

GENRE_MODEL_PATH = 'product.models.Genre'
GENRE_TRANSLATE_FIELDS = ('name',)
PRODUCT_MODEL_PATH = 'product.models.Product'
PRODUCT_TRANSLATE_FIELDS = ('name', 'description', 'brand_name')
PRODUCT_DETAIL_MODEL_PATH = 'product.models.ProductDetail'
PRODUCT_DETAIL_TRANSLATE_FIELDS = ('name', 'value',)
MARKER_MODEL_PATH = 'product.models.Marker'
MARKER_TRANSLATE_FIELDS = ('name',)
