# Generated by Django 4.2.4 on 2024-02-21 14:28

from django.db import migrations, models
import service.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productimage',
            name='products_pr_product_99a244_idx',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='can_choose_tags',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='is_read',
        ),
        migrations.AddField(
            model_name='product',
            name='can_choose_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=service.utils.uid_generate, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=service.utils.uid_generate, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='id',
            field=models.CharField(default=service.utils.uid_generate, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='site_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(default=service.utils.uid_generate, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id', 'name'], name='products_ca_id_dcb739_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id', 'level'], name='products_ca_id_5233f7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'name'], name='products_pr_id_e0f669_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'is_active'], name='products_pr_id_c8f845_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'is_active', 'name'], name='products_pr_id_78e68a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'site_avg_rating', 'site_reviews_count'], name='products_pr_id_6d995e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'created_at'], name='products_pr_id_be8089_idx'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['id', 'name'], name='products_pr_id_352356_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['id', 'name'], name='products_ta_id_8875e3_idx'),
        ),
    ]
