# Generated by Django 4.2.4 on 2024-02-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_products_pr_product_99a244_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
